name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ libboost-all-dev

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Build application
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Build and run tests
      run: |
        cd tests
        mkdir build
        cd build
        cmake ..
        make
        ./tests
